FROM gradle:jdk17-alpine
ARG PRODUCTION
ARG JDBC_DATABASE_PASSWORD
ARG JDBC_DATABASE_URL
ARG JDBC_DATABASE_USERNAME
ARG MAILJET_API_KEY
ARG MAILJET_SECRET_KEY
ARG SEKELAS_MAIL_ACCOUNT
ARG SEKELAS_WEB_URL
ARG JWT_SECRET_KEY
ARG KELAS_API_URL
ARG MINIQUIZ_API_URL

ENV PRODUCTION ${PRODUCTION}
ENV JDBC_DATABASE_PASSWORD ${JDBC_DATABASE_PASSWORD}
ENV JDBC_DATABASE_URL ${JDBC_DATABASE_URL}
ENV JDBC_DATABASE_USERNAME ${JDBC_DATABASE_USERNAME}
ENV MAILJET_API_KEY ${MAILJET_API_KEY}
ENV MAILJET_SECRET_KEY ${MAILJET_SECRET_KEY}
ENV SEKELAS_MAIL_ACCOUNT ${SEKELAS_MAIL_ACCOUNT}
ENV SEKELAS_WEB_URL ${SEKELAS_WEB_URL}
ENV JWT_SECRET_KEY ${JWT_SECRET_KEY}
ENV KELAS_API_URL ${KELAS_API_URL}
ENV MINIQUIZ_API_URL ${MINIQUIZ_API_URL}

WORKDIR /app
COPY ./build/libs/service-accounts-0.0.1-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java","-jar","service-accounts-0.0.1-SNAPSHOT.jar"]
